### ISSUE TITLE
Register name gets inserted into current buffer, Neovim 0.4.2

### ISSUE THREAD

**Issue by deathlyfrantic** [junegunn/vim-peekaboo#61] opened 2019-09-26 13:05 UTC
This is a really weird thing I've started seeing lately, I'm guessing since I updated to Neovim 0.4.2. Say I have this buffer. I've selected the second "something" and I want to copy it:
<img width="632" alt="Screen Shot 2019-09-26 at 8 59 17 AM" src="https://user-images.githubusercontent.com/7629614/65689918-f33c0500-e03b-11e9-894a-9b20094be546.png">
When I type the `"`, Peekaboo appears as normal. Then if I type `+` to choose the system clipboard register, this happens:
<img width="632" alt="Screen Shot 2019-09-26 at 9 00 25 AM" src="https://user-images.githubusercontent.com/7629614/65689999-1961a500-e03c-11e9-9a53-0a6cdf37bf27.png">
It always seems to be the second word in the fourth line where this happens. The highlighted region is using the `peekabooSelected` highlight group. The selected item does get yanked to the correct register, but now I have an errant `+` in my buffer.

Any ideas would be appreciated. This is really strange!

**Comment by deathlyfrantic** [comment] 2019-09-26 16:32
FWIW I just tested this with `nvim -u NONE` and added peekaboo as the only plugin, and this still happens. But it might be a Neovim bug? It doesn't happen with regular Vim and I don't remember it happening before I upgraded to Neovim 0.4.2.

**Comment by lourenci** [comment] 2019-09-26 16:38
I've some other weird behaviours with nvim 0.4.2 along with peekaboo. Every once in a while, when I paste from the `"` register, the window turns out into a one-line window.  I've to reopen the nvim. Do you have this problem too?

**Comment by hwalinga** [comment] 2019-12-12 14:45
Reproduced on nvim 0.4.3

https://i.imgur.com/9p5jLFk.png

**Comment by junegunn** [comment] 2019-12-12 16:05
I don't have the issue but I merged #62 as it's harmless. Please check if it fixes the issue.

**Closed** 2019-12-12 16:06 UTC

**Comment by hwalinga** [comment] 2019-12-12 16:48
Oh, yes that fixes it. Thank you.
